In [2]:
import pandas as pd
import seaborn as sns

In [3]:
insurance_data = pd.read_csv("insurance.csv")

In [5]:
copy_data = insurance_data.copy()

In [6]:
copy_data['sex'] = copy_data['sex'].map({'male': 0, 'female': 1})
copy_data['smoker'] = copy_data['smoker'].map({'yes': 1, 'no': 0})

In [8]:
copy_data.head()

   age  sex     bmi  children  smoker     region      charges
0   19    1  27.900         0       1  southwest  16884.92400
1   18    0  33.770         1       0  southeast   1725.55230
2   28    0  33.000         3       0  southeast   4449.46200
3   33    0  22.705         0       0  northwest  21984.47061
4   32    0  28.880         0       0  northwest   3866.85520

In [11]:
# one hot encoding

X = copy_data.drop(columns = ['charges'])
y = copy_data['charges']

X = pd.get_dummies(X, columns=['region'], drop_first = False, dtype=int)

In [13]:
X.head()

,age,sex,bmi,children,smoker,region_northeast,region_northwest,region_southeast,region_southwest
0,19,1,27.900,0,1,0,0,0,1
1,18,0,33.770,1,0,0,0,1,0
2,28,0,33.000,3,0,0,0,1,0
3,33,0,22.705,0,0,0,1,0,0
4,32,0,28.880,0,0,0,1,0,0

In [14]:
from sklearn.model_selection import train_test_split

# Split into 80 train and 20% test
X_train, X_test, y_train, y_test = train_test_split(
X, y, test_size=0.20, random_state=42
)

In [17]:
y_train.head()

560      9193.83850
1285     8534.67180
1142    27117.99378
969      8596.82780
486     12475.35130
Name: charges, dtype: float64

In [18]:
from sklearn.linear_model import LinearRegression

model = LinearRegression()

model.fit(X, y)

LinearRegression()

In [21]:
# Make predictions
predictions = model.predict(X_test)
print(predictions)

[ 9110.19357296  7137.91369315 37115.05462904  9551.61248039
 27133.04344439 10730.11176446   225.70883067 16873.11758652
  1118.09410781 11321.10625889 28227.14309472  9435.2224553
  4987.50843552 38350.39616955 40034.83683096 36975.10230012
 15040.17833918 35847.37923653  8831.7085101  31721.07122575
  3875.73115362 10023.62691025  2161.84776112  7213.89660063
 11515.93670226 13016.54652485 14418.48180651  6381.60166813
 10107.25694943  1741.83005255  9216.03490542 13144.1412802
  4248.09850514  3607.59913551  4299.66539258 12990.2783496
  1925.60155629  8763.61839975 33573.80097904 32405.59836056
  4060.11662976  4337.23823668 14103.99235904 11367.57329365
  8448.55170567 11927.94139229  5460.55786292  3191.72180416
 35415.7728779   8830.30971813 15521.11195037  1956.15163842
 12507.64501961  1414.99038569 12957.51136496 12615.46757705
  4271.70296949 32479.62914071 13226.38219422 12953.03044087
 14069.71246721 10309.15276056 16309.71888871  7922.21385974
 11890.58963601  4172.95816    26831.88795673 10632.86415777
  2242.34749104  6019.07724659 10733.30646229 11783.80328248
 10660.86210509  8833.04014408 11582.00791627  6421.93619783
  7344.3889043  10792.76535162  6362.80230495  8803.71968996
  3337.56987465 36758.54470781  6379.77972163 31206.91710831
 34704.79164879 35416.33089438  6735.65455711 12821.34799666
 10112.47289786 14424.46479522 17859.13098675 35111.83797726
 33319.17405573  6220.69810847 31821.58570243  9374.23682374
 29251.42999627  3356.95039435 28712.84542305  5961.60924192
  5524.47869549  1784.37194009 11082.16391145 15025.43712603
 11622.00571438  3933.64947297  9557.65270831 31446.18942191
  -163.95514087 32724.6073646   3077.67008587  9831.56212268
 14422.80234587 31945.66753642 11563.29774545  3776.10763819
 13040.76502268 32002.23443526  7928.28387984  3240.71270931
  8548.26028781 10659.71082283 15387.23759566  5223.15472243
  3939.5443871  10404.34464511 10635.61776539 11109.74960513
 14120.57374125  7018.41876424  5058.7092686   8952.71831723
  9130.89005004 12606.0186595   8244.35345992 15184.19854695
  8361.27997068 31782.40102994 36070.29659611 31854.05551177
  6074.54221608 12664.88138245  5587.62230792 14744.2632934
  2047.37332443 33038.94539212  6317.00015793  4934.48686127
 14576.22694889  6780.96929222 39099.59108634  3154.3135483
  5472.95804227 31880.66127763 11703.9219117   8424.79605466
 14746.7427172   9536.3002214  26985.93986362 33645.50169509
 14704.96262246  1796.80423098 13043.25613826  2151.4747208
  5395.91975002 11245.30551717 39919.48838543 36767.11217546
 34189.57643384  3800.38089037  7387.69281392  8618.09596899
 12415.84157716  4812.21285822  1944.39278121 31910.31432762
 25094.55997828 17064.48257961 26753.20814121 10211.81387374
 37501.17257876  -365.51670527  6762.94816658  7740.84635064
  4442.42353152  5183.45569596  5908.1757982   4202.75967367
 14946.43580649 11081.28557964  6888.37094591  2577.45284407
  1574.80543435 32044.90100008 15991.10067607 11692.61012198
  1377.90031577 12678.61249143  1610.75150127  8627.58047184
  1927.03316415 34062.58092966 10550.95120014  2656.56446622
 25591.55380717 26205.13341173  9378.09990174  2003.87560852
 12842.84709932  1053.54362622 10153.92983772 10276.61103181
 17132.88404592 26600.49957764  6590.0407435   5240.8251593
  5567.19848691 13047.21962359 10758.23594376  8095.72030643
  5218.47109067 12283.78796336 13607.98309089 35649.1866508
  4119.52471628 28681.2860384  -1030.93372488  2833.38160918
 10656.27895154 15580.75535061  4788.38718389  6930.61334149
  3845.40470524 31293.03178454  7284.13982831 11980.36505494
  5679.04730152  9324.55964784 36307.18153549  4000.52769931
  9691.95454803 31259.83353212  5826.99258561  4328.8732176
   996.64905788  4792.4929674   4572.20936817  6349.59368822
 18617.76638844 -1613.44456766  2278.66371016 10644.38072254
  3044.57940674 10242.54399223  3859.10042893  4855.55374291
 12184.16803473  6234.69485534  8153.04894682  7794.2143558
  9140.71344544 10530.32496584 27566.27024823 38827.90805402
 11822.05210618  7672.08554345 40826.37858906 12277.00107058]

In [24]:
from sklearn.metrics import r2_score

r2 = r2_score(y_test, predictions)
print(f'R2 score: {r2}')

R2 score: 0.7858188230456846

In [27]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score

# Split into 80 train and 20% test
X_train, X_test, y_train, y_test = train_test_split(
X, y, test_size=0.20, random_state=42
)

X['age_smoker'] = X['age']*X['smoker']
X['bmi_smoker'] = X['bmi']*X['smoker']

model = LinearRegression()
model.fit(X, y)

# Make predictions
y_pred = model.predict(X_test)

r2 = r2_score(y_test, y_pred)
print(f'R2 score: {r2}')

R2 score: 0.8669857364353448