In [1]:
import pandas as pd

In [29]:
df = pd.read_csv("globalAirQuality.csv")
df[(df["aqi"] > 200) | (df["temperature"] > 30)][["city", "aqi"]]

df.query("aqi > 200")[["city", "aqi"]]

           city  aqi
745      London  214
8941      Osaka  204
12956  Auckland  225
14555    Manila  206
17458  Helsinki  202
17529  Helsinki  231
17815    Zurich  203

In [54]:
df = pd.read_csv("raw_data.csv")

cleaned_data = df.copy()
avg_age = cleaned_data["age"].mean()
cleaned_data["age"] = cleaned_data["age"].fillna(avg_age)
cleaned_data.drop_duplicates()

    id          name    age country   gender   income
0    1      John Doe  29.00     USA     Male  55000.0
2    2    Jane Smith  32.75  Canada   Female  62000.0
3    3          Alex  32.75     USA  Unknown  47000.0
4    4  Maria Garcia  34.00   Spain   Female      NaN
5    5        Li Wei  27.00   China     Male  51000.0
6    6           NaN  45.00   India   Female  73000.0
7    7    Ahmed Khan  38.00     NaN     Male  68000.0
8    8    Rachel Lee  29.00     USA   Female  62000.0
9    9   Carlos Ruiz  32.75  Mexico     Male  45000.0
10  10   Emily Davis  31.00     USA      NaN  58000.0

In [55]:
df

    id          name   age country   gender   income
0    1      John Doe  29.0     USA     Male  55000.0
1    1      John Doe  29.0     USA     Male  55000.0
2    2    Jane Smith   NaN  Canada   Female  62000.0
3    3          Alex   NaN     USA  Unknown  47000.0
4    4  Maria Garcia  34.0   Spain   Female      NaN
5    5        Li Wei  27.0   China     Male  51000.0
6    6           NaN  45.0   India   Female  73000.0
7    7    Ahmed Khan  38.0     NaN     Male  68000.0
8    8    Rachel Lee  29.0     USA   Female  62000.0
9    9   Carlos Ruiz   NaN  Mexico     Male  45000.0
10  10   Emily Davis  31.0     USA      NaN  58000.0